title: "Hello World"
author: "Henry Bambury"
description: "Work in progress"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Home}
  - {file: "education.html", icon : graduation-cap, title: Education}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Contact, icon: envelope, url: "https://www.di.ens.fr/contact?user=253"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
